# DataSource Config
spring:
  datasource:
    driver-calss-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=ture&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379